name: flutter_segment
description: Flutter implementation of Segment Analytics for iOS, Android
version: 4.0.0
homepage: https://www.wildflowers.love/
repository: https://github.com/lisa1357mae/flutter-segment
issue_tracker: https://github.com/lisa1357mae/flutter-segment/issues
documentation: https://github.com/lisa1357mae/flutter-segment#readme

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">2.0.0"
q
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_segment
        pluginClass: FlutterSegmentPlugin
      ios:
        pluginClass: FlutterSegmentPlugin
